---
- name: This playbook will install and deploy a simple webpage
  hosts: servers
  become: yes
  tasks:
    - name: install nginx
      yum:
        name: nginx
        state: latest

    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create /var/www/html directory
      file:
        path: /var/www/html
        state: directory

    - name: Deploy webpage
      copy:
        src: index.html
        dest: /var/www/html